// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtwEAfE8FAKQnrAfba4g-jS8EGPvfxlww',
    appId: '1:300699093367:web:7c35f26230897fd344f972',
    messagingSenderId: '300699093367',
    projectId: 'taskhero-2026',
    authDomain: 'taskhero-2026.firebaseapp.com',
    storageBucket: 'taskhero-2026.firebasestorage.app',
    measurementId: 'G-SGF9SLKP8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUFED4ANcERy8rsX_8QrMwTRKHLHJIAg',
    appId: '1:300699093367:android:b9f9974749070a0744f972',
    messagingSenderId: '300699093367',
    projectId: 'taskhero-2026',
    storageBucket: 'taskhero-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYBiy-XZzMMZuPsUz38Ik_EjT--pKlTo',
    appId: '1:300699093367:ios:d2e8014fe315f07644f972',
    messagingSenderId: '300699093367',
    projectId: 'taskhero-2026',
    storageBucket: 'taskhero-2026.firebasestorage.app',
    iosBundleId: 'com.example.taskhero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVYBiy-XZzMMZuPsUz38Ik_EjT--pKlTo',
    appId: '1:300699093367:ios:d2e8014fe315f07644f972',
    messagingSenderId: '300699093367',
    projectId: 'taskhero-2026',
    storageBucket: 'taskhero-2026.firebasestorage.app',
    iosBundleId: 'com.example.taskhero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtwEAfE8FAKQnrAfba4g-jS8EGPvfxlww',
    appId: '1:300699093367:web:5ceeb77b03fa34ef44f972',
    messagingSenderId: '300699093367',
    projectId: 'taskhero-2026',
    authDomain: 'taskhero-2026.firebaseapp.com',
    storageBucket: 'taskhero-2026.firebasestorage.app',
    measurementId: 'G-7LNS082MD8',
  );
}
